language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t azdocker1920/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true azdocker1920/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-051763998226"
  bucker_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"