language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t azdocker1920/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true azdocker1920/docker-react npm run test -- --coverage